version: "3.2"
services:
  wordpress:
    image: wordpress:php7.2-apache
    ports: 
      -80:80
     environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    links:
      - mysql:mysql
      
      
      
     
