version: "3.2"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend:
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: php-register
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
    ports:
      - "8081:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: apache-register
